using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Globalization;
using System.Linq;
using System.Text;

[Generator]
public class RegistrationGenerator : IIncrementalGenerator
{
    // Diagnostic descriptors
    private static readonly DiagnosticDescriptor InvalidBaseTypeError = new DiagnosticDescriptor(
        id: "REG001",
        title: "Invalid RegisterDefinition usage",
        messageFormat: "The type '{0}' must inherit from RenData.SaveLoad.PersistClass to use RegisterDefinition attribute",
        category: "Registration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Types with RegisterDefinition attribute must inherit from PersistClass.");

    private static readonly DiagnosticDescriptor NotPartialClassError = new DiagnosticDescriptor(
        id: "REG002",
        title: "Class must be partial",
        messageFormat: "The type '{0}' must be declared as a partial class to use RegisterDefinition attribute",
        category: "Registration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingChunkIdError = new DiagnosticDescriptor(
        id: "REG003",
        title: "Missing chunk ID",
        messageFormat: "The RegisterDefinition attribute on '{0}' must have a chunk ID parameter",
        category: "Registration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("RegisterDefinitionAttribute.g.cs", @"// <auto-generated/>
using System;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class RegisterDefinitionAttribute : Attribute
{
    public uint ChunkId { get; }
    
    public RegisterDefinitionAttribute(uint chunkId)
    {
        ChunkId = chunkId;
    }
}
");
        });

        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations,
            static (spc, source) => Execute(source!, spc));
    }

    static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax c
            && c.AttributeLists.Count > 0;
    }

    static AnalysisResult? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclarationSyntax);

        if (classSymbol == null)
            return null;

        // Check for RegisterDefinition attribute
        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name == "RegisterDefinitionAttribute" ||
                attribute.AttributeClass?.Name == "RegisterDefinition")
            {
                var location = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation()
                    ?? classDeclarationSyntax.Identifier.GetLocation();

                // Check if class is partial
                if (!classDeclarationSyntax.Modifiers.Any(SyntaxKind.PartialKeyword))
                {
                    return new AnalysisResult
                    {
                        HasError = true,
                        Diagnostic = Diagnostic.Create(
                            NotPartialClassError,
                            location,
                            classSymbol.Name)
                    };
                }

                // Check if the class inherits from PersistClass
                if (!InheritsFromPersistClass(classSymbol))
                {
                    return new AnalysisResult
                    {
                        HasError = true,
                        Diagnostic = Diagnostic.Create(
                            InvalidBaseTypeError,
                            location,
                            classSymbol.Name)
                    };
                }

                // Get the chunk ID from the attribute
                if (attribute.ConstructorArguments.Length == 0)
                {
                    return new AnalysisResult
                    {
                        HasError = true,
                        Diagnostic = Diagnostic.Create(
                            MissingChunkIdError,
                            location,
                            classSymbol.Name)
                    };
                }

                var chunkIdArg = attribute.ConstructorArguments[0];
                var chunkIdExpression = BuildIdExpr(chunkIdArg);

                // Everything is valid, generate the registration
                var accessibility = GetAccessibilityString(classSymbol.DeclaredAccessibility);

                return new AnalysisResult
                {
                    HasError = false,
                    ClassToGenerate = new ClassToGenerate
                    {
                        ClassName = classSymbol.Name,
                        Namespace = classSymbol.ContainingNamespace.ToDisplayString(),
                        Accessibility = accessibility,
                        ChunkIdExpression = chunkIdExpression
                    }
                };
            }
        }

        return null;
    }

    private static string BuildIdExpr(TypedConstant arg)
    {
        // Accept either: uint literal, or any enum constant.
        if (arg.Kind == TypedConstantKind.Primitive && arg.Value is uint u)
            return u.ToString(CultureInfo.InvariantCulture) + "u";

        if (arg.Kind == TypedConstantKind.Enum)
        {
            // Arg.Value is the underlying integral value (boxed)
            // We normalize to UInt64 then cast to uint in generated code.
            ulong val = Convert.ToUInt64(arg.Value, CultureInfo.InvariantCulture);
            return val.ToString(CultureInfo.InvariantCulture) + "u";
        }

        // If someone passes an int literal etc., make a best effort
        if (arg.Kind == TypedConstantKind.Primitive && arg.Value is IConvertible conv)
        {
            ulong val = Convert.ToUInt64(conv, CultureInfo.InvariantCulture);
            return val.ToString(CultureInfo.InvariantCulture) + "u";
        }

        // Fallback – compile error is preferable to wrong code
        return "default(uint)";
    }

    static string GetAccessibilityString(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.Private => "private",
            _ => "internal"
        };
    }

    static bool InheritsFromPersistClass(INamedTypeSymbol classSymbol)
    {
        var baseType = classSymbol.BaseType;

        while (baseType != null)
        {
            var fullName = baseType.ToDisplayString();

            if (fullName == "RenData.SaveLoad.PersistClass" ||
                fullName == "global::RenData.SaveLoad.PersistClass" ||
                (baseType.Name == "PersistClass" &&
                 baseType.ContainingNamespace?.ToDisplayString() == "RenData.SaveLoad"))
            {
                return true;
            }

            baseType = baseType.BaseType;
        }

        return false;
    }

    static void Execute(AnalysisResult result, SourceProductionContext context)
    {
        if (result.HasError)
        {
            context.ReportDiagnostic(result.Diagnostic!);
            return;
        }

        var source = GeneratePartialClass(result.ClassToGenerate!);
        context.AddSource($"{result.ClassToGenerate!.ClassName}.Registration.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }

    static string GeneratePartialClass(ClassToGenerate classToGenerate)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine();

        // Add namespace if needed
        if (!string.IsNullOrEmpty(classToGenerate.Namespace))
        {
            sb.AppendLine($"namespace {classToGenerate.Namespace}");
            sb.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(classToGenerate.Namespace) ? "" : "    ";

        // Generate partial class with registration
        sb.AppendLine($"{indent}{classToGenerate.Accessibility} partial class {classToGenerate.ClassName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private static readonly uint _chunkId = {classToGenerate.ChunkIdExpression};");
        sb.AppendLine($"{indent}    private static int _registrationCount = 0;");
        sb.AppendLine($"{indent}    private static RenData.SaveLoad.SimplePersistFactoryClass<{classToGenerate.ClassName}> _persistFactory = ");
        sb.AppendLine($"{indent}        new({classToGenerate.ChunkIdExpression});");
        sb.AppendLine();
        var methodName = $"Initialize{classToGenerate.ClassName}Registration";
        sb.AppendLine($"{indent}    [ModuleInitializer]");
        sb.AppendLine($"{indent}    internal static void {methodName}()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        // Ensure single initialization using Interlocked");
        sb.AppendLine($"{indent}        if (Interlocked.Exchange(ref _registrationCount, 1) != 0)");
        sb.AppendLine($"{indent}            return;");
        sb.AppendLine();
        sb.AppendLine($"{indent}        try");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            RenData.Definitions.DefinitionMgrClass.RegisteredDefinitions.TryAdd(_chunkId, \"{classToGenerate.ClassName}\");");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}        catch (Exception ex)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            // Log or handle registration errors");
        sb.AppendLine($"{indent}            System.Diagnostics.Debug.WriteLine($\"Failed to register {{nameof({classToGenerate.ClassName})}}: {{ex}}\");");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}        GC.KeepAlive(_persistFactory);");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// Gets the persist factory for this class.");
        sb.AppendLine($"{indent}    /// </summary>");
        //sb.AppendLine($"{indent}    internal static RenData.SaveLoad.SimplePersistFactoryClass<{classToGenerate.ClassName}> PersistFactory => _persistFactory;");
        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(classToGenerate.Namespace))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    class AnalysisResult
    {
        public bool HasError { get; set; }
        public Diagnostic? Diagnostic { get; set; }
        public ClassToGenerate? ClassToGenerate { get; set; }
    }

    class MethodValidationResult
    {
        public bool HasError { get; set; }
        public DiagnosticDescriptor? Descriptor { get; set; }
    }

    class ClassToGenerate
    {
        public string ClassName { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string Accessibility { get; set; } = "internal";
        public string ChunkIdExpression { get; set; } = "";
    }
}