namespace ObjectsReader;
public enum TransitionType
{
    LADDER_EXIT_TOP,
    LADDER_EXIT_BOTTOM,
    LADDER_ENTER_TOP,
    LADDER_ENTER_BOTTOM,
    LEGACY_VEHICLE_ENTER_0,
    LEGACY_VEHICLE_ENTER_1,
    LEGACY_VEHICLE_EXIT_0,
    LEGACY_VEHICLE_EXIT_1,
    VEHICLE_ENTER,
    VEHICLE_EXIT,
};