namespace RenData.IDs;

public static class ChunkId
{
    public const uint CHUNKID_SAVELOAD_BEGIN = 0x00000100;
    public const uint CHUNKID_SAVELOAD_DEFMGR = 0x00000101;
    public const uint CHUNKID_TWIDDLER = 0x00000102;
    public const uint CHUNKID_WW3D_BEGIN = 0x00010000;
    public const uint CHUNKID_WWPHYS_BEGIN = 0x00020000;
    public const uint CHUNKID_WWAUDIO_BEGIN = 0x00030000;
    public const uint CHUNKID_COMBAT_BEGIN = 0x00040000;
    public const uint CHUNKID_COMMANDO_EDITOR_BEGIN = 0x00050000;
    public const uint CHUNKID_PHYSTEST_BEGIN = 0x00060000;
    public const uint CHUNKID_COMMANDO_BEGIN = 0x00070000;
    public const uint CHUNKID_WWMATH_BEGIN = 0x00080000;
    public const uint CHUNKID_WWTRANSLATEDB_BEGIN = 0x0009000;

    public const uint CHUNKID_COMBAT = ChunkId.CHUNKID_COMBAT_BEGIN;          // 0x00040000
    public const uint CHUNKID_TIMER = ChunkId.CHUNKID_COMBAT_BEGIN + 1;      // 0x00040001
    public const uint CHUNKID_TIMER_GAME_OBJ = ChunkId.CHUNKID_COMBAT_BEGIN + 2;      // 0x00040002

    public const uint CHUNKID_GAME_OBJECTS_BEGIN = ChunkId.CHUNKID_COMBAT_BEGIN + 0x100;  // 0x00040100

    public const uint CHUNKID_GAME_OBJECT_BULLET = 0x00040101;

    public const uint CHUNKID_GAME_OBJECT_C4 = 0x00040102;
    public const uint CHUNKID_GAME_OBJECT_DEF_C4 = 0x00040103;

    public const uint CHUNKID_GAME_OBJECT_COMMANDO = 0x00040104;
    public const uint CHUNKID_GAME_OBJECT_DEF_COMMANDO = 0x00040105;

    public const uint CHUNKID_GAME_OBJECT_POWERUP = 0x00040106;
    public const uint CHUNKID_GAME_OBJECT_DEF_POWERUP = 0x00040107;

    public const uint CHUNKID_GAME_OBJECT_SAMSITE = 0x00040108;
    public const uint CHUNKID_GAME_OBJECT_DEF_SAMSITE = 0x00040109;

    public const uint CHUNKID_GAME_OBJECT_SIMPLE = 0x0004010A;
    public const uint CHUNKID_GAME_OBJECT_DEF_SIMPLE = 0x0004010B;

    public const uint XXXCHUNKID_GAME_OBJECT_SIMPLE3 = 0x0004010C;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_SIMPLE3 = 0x0004010D;

    public const uint CHUNKID_GAME_OBJECT_SOLDIER = 0x0004010E;
    public const uint CHUNKID_GAME_OBJECT_DEF_SOLDIER = 0x0004010F;

    public const uint CHUNKID_GAME_OBJECT_VEHICLE = 0x00040110;

    public const uint CHUNKID_GAME_OBJECT_VISUAL = 0x00040111;
    public const uint CHUNKID_GAME_OBJECT_TIMED_VISUAL = 0x00040112;
    public const uint CHUNKID_GAME_OBJECT_ANIMATED_VISUAL = 0x00040113;
    public const uint CHUNKID_GAME_OBJECT_PROJECTILE_VISUAL = 0x00040114;
    public const uint CHUNKID_GAME_OBJECT_XXXXXXXXXXXXXXXXX = 0x00040115;

    public const uint XXXCHUNKID_GAME_OBJECT_TANK = 0x00040116;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_TANK = 0x00040117;

    public const uint XXXCHUNKID_GAME_OBJECT_TURRET = 0x00040118;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_TURRET = 0x00040119;

    public const uint XXXCHUNKID_GAME_OBJECT_BIKE = 0x0004011A;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_BIKE = 0x0004011B;

    public const uint XXXCHUNKID_GAME_OBJECT_FLYING = 0x0004011C;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_FLYING = 0x0004011D;

    public const uint XXXCHUNKID_GAME_OBJECT_CAR = 0x0004011E;
    public const uint XXXCHUNKID_GAME_OBJECT_DEF_CAR = 0x0004011F;

    public const uint CHUNKID_SPAWNER = 0x00040120;
    public const uint CHUNKID_SPAWNER_DEF = 0x00040121;

    public const uint CHUNKID_GAME_OBJECT_ZONE = 0x00040122;
    public const uint CHUNKID_GAME_OBJECT_DEF_ZONE = 0x00040123;

    public const uint CHUNKID_GAME_OBJECT_SCRIPT_ZONE = 0x00040122;
    public const uint CHUNKID_GAME_OBJECT_DEF_SCRIPT_ZONE = 0x00040123;

    public const uint CHUNKID_GAME_OBJECT_TRANSITION = 0x00040124;
    public const uint CHUNKID_GAME_OBJECT_DEF_TRANSITION = 0x00040125;

    // MISC ITEMS
    public const uint CHUNKID_BACKGROUND_MGR = 0x00040126;
    public const uint CHUNKID_WEAPON_DEF = 0x00040127;
    public const uint CHUNKID_AMMO_DEF = 0x00040128;

    public const uint CHUNKID_GAME_OBJECT_DEF_VEHICLE = 0x00040129;

    public const uint CHUNKID_EXPLOSION_DEF = 0x0004012A;

    public const uint CHUNKID_GAME_OBJECT_CINEMATIC = 0x0004012B;
    public const uint CHUNKID_GAME_OBJECT_DEF_CINEMATIC = 0x0004012C;

    public const uint CHUNKID_GAME_OBJECT_DAMAGE_ZONE = 0x0004012D;
    public const uint CHUNKID_GAME_OBJECT_DEF_DAMAGE_ZONE = 0x0004012E;

    public const uint CHUNKID_GAME_OBJECT_SPECIAL_EFFECTS = 0x0004012F;
    public const uint CHUNKID_GAME_OBJECT_DEF_SPECIAL_EFFECTS = 0x00040130;

    public const uint CHUNKID_GAME_OBJECT_SAKURA_BOSS = 0x00040131;
    public const uint CHUNKID_GAME_OBJECT_DEF_SAKURA_BOSS = 0x00040132;

    public const uint CHUNKID_GAME_OBJECT_BUILDING = 0x00040133;
    public const uint CHUNKID_GAME_OBJECT_DEF_BUILDING = 0x00040134;

    public const uint CHUNKID_GAME_OBJECT_BEACON = 0x00040135;
    public const uint CHUNKID_GAME_OBJECT_DEF_BEACON = 0x00040136;

    public const uint CHUNKID_GAME_OBJECT_REFINERY = 0x00040137;
    public const uint CHUNKID_GAME_OBJECT_DEF_REFINERY = 0x00040138;

    public const uint CHUNKID_GAME_OBJECT_POWERPLANT = 0x00040139;
    public const uint CHUNKID_GAME_OBJECT_DEF_POWERPLANT = 0x0004013A;

    public const uint CHUNKID_GAME_OBJECT_SOLDIER_FACTORY = 0x0004013B;
    public const uint CHUNKID_GAME_OBJECT_DEF_SOLDIER_FACTORY = 0x0004013C;

    public const uint CHUNKID_GAME_OBJECT_VEHICLE_FACTORY = 0x0004013D;
    public const uint CHUNKID_GAME_OBJECT_DEF_VEHICLE_FACTORY = 0x0004013E;

    public const uint CHUNKID_GAME_OBJECT_AIRSTRIP = 0x0004013F;
    public const uint CHUNKID_GAME_OBJECT_DEF_AIRSTRIP = 0x00040140;

    public const uint CHUNKID_GAME_OBJECT_WARFACTORY = 0x00040141;
    public const uint CHUNKID_GAME_OBJECT_DEF_WARFACTORY = 0x00040142;

    public const uint CHUNKID_GAME_OBJECT_COMCENTER = 0x00040143;
    public const uint CHUNKID_GAME_OBJECT_DEF_COMCENTER = 0x00040144;

    public const uint CHUNKID_GAME_OBJECT_REPAIR_BAY = 0x00040145;
    public const uint CHUNKID_GAME_OBJECT_DEF_REPAIR_BAY = 0x00040146;

    public const uint CHUNKID_MAPMGR = 0x00040147;
    public const uint CHUNKID_ENCYCLOPEDIAMGR = 0x00040148;

    public const uint CHUNKID_GAME_OBJECT_MENDOZA_BOSS = 0x00040149;
    public const uint CHUNKID_GAME_OBJECT_DEF_MENDOZA_BOSS = 0x0004014A;

    public const uint CHUNKID_GAME_OBJECT_RAVESHAW_BOSS = 0x0004014B;
    public const uint CHUNKID_GAME_OBJECT_DEF_RAVESHAW_BOSS = 0x0004014C;


    public const uint CHUNKID_GAME_OBJECT_OBSERVERS_BEGIN = ChunkId.CHUNKID_COMBAT_BEGIN + 0x200; // 0x00040200
    public const uint CHUNKID_SOLDIER_OBSERVER = 0x00040201;
    public const uint CHUNKID_BEACON_MONITOR = 0x00040202;

    // --- Buildings ---
    public const uint CHUNKID_BUILDINGS_BEGIN = CHUNKID_COMBAT_BEGIN + 0x301; // 0x00040301
    public const uint CHUNKID_BUILDING = CHUNKID_BUILDINGS_BEGIN + 1;  // 0x00040302

    // --- Building Defs ---
    public const uint CHUNKID_BUILDINGS_DEF_BEGIN = CHUNKID_COMBAT_BEGIN + 0x401; // 0x00040401
    public const uint CHUNKID_BUILDING_DEF = CHUNKID_BUILDINGS_DEF_BEGIN + 1; // 0x00040402

    // --- Action Codes ---
    public const uint CHUNKID_ACTION_CODE_BEGIN = CHUNKID_COMBAT_BEGIN + 0x500; // 0x00040500
    public const uint CHUNKID_ACTION_CODE_FOLLOW_INPUT = CHUNKID_ACTION_CODE_BEGIN + 1; // 0x00040501
    public const uint CHUNKID_ACTION_CODE_STAND = CHUNKID_ACTION_CODE_BEGIN + 2; // 0x00040502
    public const uint CHUNKID_ACTION_CODE_GOTO = CHUNKID_ACTION_CODE_BEGIN + 3; // 0x00040503
    public const uint CHUNKID_ACTION_CODE_ENTER_EXIT = CHUNKID_ACTION_CODE_BEGIN + 4; // 0x00040504
    public const uint CHUNKID_ACTION_CODE_ATTACK = CHUNKID_ACTION_CODE_BEGIN + 5; // 0x00040505
    public const uint CHUNKID_ACTION_CODE_PLAY_ANIMATION = CHUNKID_ACTION_CODE_BEGIN + 6; // 0x00040506
    public const uint CHUNKID_ACTION_CODE_FACE_LOCATION = CHUNKID_ACTION_CODE_BEGIN + 7; // 0x00040507
    public const uint CHUNKID_ACTION_CODE_DIVE = CHUNKID_ACTION_CODE_BEGIN + 8; // 0x00040508
    public const uint CHUNKID_ACTION_CODE_CONVERSATION = CHUNKID_ACTION_CODE_BEGIN + 9; // 0x00040509
    public const uint CHUNKID_ACTION_CODE_DOCK = CHUNKID_ACTION_CODE_BEGIN + 10; // 0x0004050A

    // --- Global Settings ---
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF = CHUNKID_COMBAT_BEGIN + 0x600; // 0x00040600
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_HUMAN_LOITER = CHUNKID_GLOBAL_SETTINGS_DEF + 1; // 0x00040601
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_GENERAL = CHUNKID_GLOBAL_SETTINGS_DEF + 2; // 0x00040602
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_HUD = CHUNKID_GLOBAL_SETTINGS_DEF + 3; // 0x00040603
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_EVA = CHUNKID_GLOBAL_SETTINGS_DEF + 4; // 0x00040604
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_CHAR_CLASS = CHUNKID_GLOBAL_SETTINGS_DEF + 5; // 0x00040605
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_HUMAN_ANIM_OVERRIDE = CHUNKID_GLOBAL_SETTINGS_DEF + 6; // 0x00040606
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_PURCHASE = CHUNKID_GLOBAL_SETTINGS_DEF + 7; // 0x00040607
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_TEAM_PURCHASE = CHUNKID_GLOBAL_SETTINGS_DEF + 8; // 0x00040608
    public const uint CHUNKID_GLOBAL_SETTINGS_DEF_CNCMODE = CHUNKID_GLOBAL_SETTINGS_DEF + 9; // 0x00040609

    // --- Conversation Manager ---
    public const uint CHUNKID_CONVERSATION_MGR = CHUNKID_COMBAT_BEGIN + 0x700; // 0x00040700

    // --- Weather Manager ---
    public const uint CHUNKID_WEATHER_MGR = CHUNKID_COMBAT_BEGIN + 0x800; // 0x00040800

    // --- Player Data ---
    public const uint CHUNKID_PLAYER_DATA = CHUNKID_COMBAT_BEGIN + 0x900; // 0x00040900
    public const uint CHUNKID_PLAYER_DATA_CPLAYER = CHUNKID_PLAYER_DATA + 1;      // 0x00040901

    public const uint PHYSICS_CHUNKID_STATIC_DATA_SUBSYSTEM = 0x00020000; // = CHUNKID_WWPHYS_BEGIN
    public const uint PHYSICS_CHUNKID_STATIC_OBJECTS_SUBSYSTEM = 0x00020001;
    public const uint PHYSICS_CHUNKID_DYNAMIC_DATA_SUBSYSTEM = 0x00020050; // +0x50

    // Individual persist object chunk IDs (start at +0x100)
    public const uint PHYSICS_CHUNKID_DECORATIONPHYS = 0x00020100; // +0x100
    public const uint PHYSICS_CHUNKID_HUMANPHYS = 0x00020101;
    public const uint PHYSICS_CHUNKID_LIGHTPHYS = 0x00020102;
    public const uint PHYSICS_CHUNKID_MOTORCYCLE = 0x00020103;
    public const uint PHYSICS_CHUNKID_MOTORVEHICLE = 0x00020104;
    public const uint PHYSICS_CHUNKID_PHYS3 = 0x00020105;
    public const uint PHYSICS_CHUNKID_PROJECTILE = 0x00020106;
    public const uint PHYSICS_CHUNKID_RENDEROBJPHYS = 0x00020107;
    public const uint PHYSICS_CHUNKID_RIGIDBODY = 0x00020108;
    public const uint PHYSICS_CHUNKID_STATICPHYS = 0x00020109;
    public const uint PHYSICS_CHUNKID_WHEELEDVEHICLE = 0x0002010A;
    public const uint PHYSICS_CHUNKID_STATICANIMPHYS = 0x0002010B;
    public const uint PHYSICS_CHUNKID_TIMEDDECORATIONPHYS = 0x0002010C;
    public const uint PHYSICS_CHUNKID_VEHICLEPHYS = 0x0002010D;
    public const uint PHYSICS_CHUNKID_TRACKEDVEHICLE = 0x0002010E;
    public const uint PHYSICS_CHUNKID_VTOLVEHICLE = 0x0002010F;
    public const uint PHYSICS_CHUNKID_WAYPATH = 0x00020110;
    public const uint PHYSICS_CHUNKID_WAYPOINT = 0x00020111;
    public const uint PHYSICS_CHUNKID_DYNAMICANIMPHYS = 0x00020112;
    public const uint PHYSICS_CHUNKID_SHAKEABLESTATICPHYS = 0x00020113;
    public const uint PHYSICS_CHUNKID_ACCESSIBLEPHYS = 0x00020114;

    // Definition object chunk IDs (start at +0x500)
    public const uint PHYSICS_CHUNKID_DECOPHYSDEF = 0x00020500; // +0x500
    public const uint PHYSICS_CHUNKID_HUMANPHYSDEF = 0x00020501;
    public const uint PHYSICS_CHUNKID_LIGHTPHYSDEF = 0x00020502;
    public const uint PHYSICS_CHUNKID_MOTORCYCLEDEF = 0x00020503;
    public const uint PHYSICS_CHUNKID_MOTORVEHICLEDEF = 0x00020504;
    public const uint PHYSICS_CHUNKID_PHYS3DEF = 0x00020505;
    public const uint PHYSICS_CHUNKID_PROJECTILEDEF = 0x00020506;
    public const uint PHYSICS_CHUNKID_RIGIDBODYDEF = 0x00020507;
    public const uint PHYSICS_CHUNKID_STATICPHYSDEF = 0x00020508;
    public const uint PHYSICS_CHUNKID_WHEELEDVEHICLEDEF = 0x00020509;
    public const uint PHYSICS_CHUNKID_STATICANIMPHYSDEF = 0x0002050A;
    public const uint PHYSICS_CHUNKID_TIMEDDECOPHYSDEF = 0x0002050B;
    public const uint PHYSICS_CHUNKID_VEHICLEPHYSDEF = 0x0002050C;
    public const uint PHYSICS_CHUNKID_TRACKEDVEHICLEDEF = 0x0002050D;
    public const uint PHYSICS_CHUNKID_VTOLVEHICLEDEF = 0x0002050E;
    public const uint PHYSICS_CHUNKID_DYNAMICANIMPHYSDEF = 0x0002050F;
    public const uint PHYSICS_CHUNKID_SHAKEABLESTATICPHYSDEF = 0x00020510;
    public const uint PHYSICS_CHUNKID_ACCESSIBLEPHYSDEF = 0x00020511;

    // External persist object chunk IDs (start at +0xA00)
    public const uint PHYSICS_CHUNKID_DOORPHYS = 0x00020A00; // +0xA00
    public const uint PHYSICS_CHUNKID_ELEVATORPHYS = 0x00020A01;
    public const uint PHYSICS_CHUNKID_DAMAGEABLESTATICPHYS = 0x00020A02;
    public const uint PHYSICS_CHUNKID_BUILDINGAGGREGATE = 0x00020A03;

    // External persist object def chunk IDs (start at +0xC00)
    public const uint PHYSICS_CHUNKID_DOORPHYSDEF = 0x00020C00; // +0xC00
    public const uint PHYSICS_CHUNKID_ELEVATORPHYSDEF = 0x00020C01;
    public const uint PHYSICS_CHUNKID_DAMAGEABLESTATICPHYSDEF = 0x00020C02;
    public const uint PHYSICS_CHUNKID_BUILDINGAGGREGATEDEF = 0x00020C03;

    // Converted enum values from anonymous enums to public const uint

    // Editor chunk IDs (was anonymous enum starting at CHUNKID_COMMANDO_EDITOR_BEGIN)
    public const uint CHUNKID_TERRAIN_DEF = CHUNKID_COMMANDO_EDITOR_BEGIN;
    public const uint CHUNKID_TILE_DEF = CHUNKID_TERRAIN_DEF + 1;
    public const uint CHUNKID_LIGHT_DEF = CHUNKID_TILE_DEF + 1;
    public const uint CHUNKID_WAYPATH_DEF = CHUNKID_LIGHT_DEF + 1;
    public const uint CHUNKID_EDITOR_ZONE_DEF = CHUNKID_WAYPATH_DEF + 1;
    public const uint CHUNKID_TRANSITION_DEF = CHUNKID_EDITOR_ZONE_DEF + 1;
    public const uint CHUNKID_EDITOR_PHYS = CHUNKID_TRANSITION_DEF + 1;
    public const uint CHUNKID_PRESET = CHUNKID_EDITOR_PHYS + 1;
    public const uint CHUNKID_PRESETMGR = CHUNKID_PRESET + 1;
    public const uint CHUNKID_NODEMGR = CHUNKID_PRESETMGR + 1;
    public const uint CHUNKID_NODE_TERRAIN = CHUNKID_NODEMGR + 1;
    public const uint CHUNKID_NODE_TILE = CHUNKID_NODE_TERRAIN + 1;
    public const uint CHUNKID_NODE_OBJECTS = CHUNKID_NODE_TILE + 1;
    public const uint CHUNKID_NODE_LIGHT = CHUNKID_NODE_OBJECTS + 1;
    public const uint CHUNKID_NODE_OLD_SOUND = CHUNKID_NODE_LIGHT + 1;
    public const uint CHUNKID_NODE_WAYPATH = CHUNKID_NODE_OLD_SOUND + 1;
    public const uint CHUNKID_NODE_ZONE = CHUNKID_NODE_WAYPATH + 1;
    public const uint CHUNKID_NODE_TRANSITION = CHUNKID_NODE_ZONE + 1;
    public const uint CHUNKID_EDITOR_SAVELOAD = CHUNKID_NODE_TRANSITION + 1;
    public const uint CHUNKID_XXX = CHUNKID_EDITOR_SAVELOAD + 1;
    public const uint CHUNKID_NODE_TERRAIN_SECTION = CHUNKID_XXX + 1;
    public const uint CHUNKID_NODE_VIS_POINT = CHUNKID_NODE_TERRAIN_SECTION + 1;
    public const uint CHUNKID_VIS_POINT_DEF = CHUNKID_NODE_VIS_POINT + 1;
    public const uint CHUNKID_NODE_PATHFIND_START = CHUNKID_VIS_POINT_DEF + 1;
    public const uint CHUNKID_PATHFIND_START_DEF = CHUNKID_NODE_PATHFIND_START + 1;
    public const uint CHUNKID_DUMMY_OBJECT_DEF = CHUNKID_PATHFIND_START_DEF + 1;
    public const uint CHUNKID_DUMMY_OBJECT = CHUNKID_DUMMY_OBJECT_DEF + 1;
    public const uint CHUNKID_NODE_WAYPOINT = CHUNKID_DUMMY_OBJECT + 1;
    public const uint CHUNKID_COVERSPOT_DEF = CHUNKID_NODE_WAYPOINT + 1;
    public const uint CHUNKID_NODE_COVER_ATTACK_POINT = CHUNKID_COVERSPOT_DEF + 1;
    public const uint CHUNKID_NODE_COVER_SPOT = CHUNKID_NODE_COVER_ATTACK_POINT + 1;
    public const uint CHUNKID_NODE_DAMAGE_ZONE = CHUNKID_NODE_COVER_SPOT + 1;
    public const uint XXX_CHUNKID_NODE_BUILDING = CHUNKID_NODE_DAMAGE_ZONE + 1;
    public const uint CHUNKID_NODE_SPAWN_POINT = XXX_CHUNKID_NODE_BUILDING + 1;
    public const uint CHUNKID_NODE_SPAWNER = CHUNKID_NODE_SPAWN_POINT + 1;
    public const uint CHUNKID_NODE_BUILDING = CHUNKID_NODE_SPAWNER + 1;
    public const uint CHUNKID_NODE_BUILDING_CHILD = CHUNKID_NODE_BUILDING + 1;
    public const uint CHUNKID_NODE_NEW_SOUND = CHUNKID_NODE_BUILDING_CHILD + 1;
    public const uint CHUNKID_EDITOR_ONLY_OBJECTS_DEF = CHUNKID_NODE_NEW_SOUND + 1;
    public const uint CHUNKID_EDITOR_ONLY_OBJECTS = CHUNKID_EDITOR_ONLY_OBJECTS_DEF + 1;
    public const uint CHUNKID_EDITOR_PATHFIND_IMPORTER_EXPORTER = CHUNKID_EDITOR_ONLY_OBJECTS + 1;
    public const uint CHUNKID_EDITOR_LIGHT_SOLVE_SAVELOAD = CHUNKID_EDITOR_PATHFIND_IMPORTER_EXPORTER + 1;
    public const uint CHUNKID_HEIGHTFIELD_MGR = CHUNKID_EDITOR_LIGHT_SOLVE_SAVELOAD + 1;

    // CLASSID values that were in anonymous enum; reference ClassId constants
    public const uint CLASSID_EDITOR_START = (uint)(ClassId.CLASSID_EDITOR_OBJECTS + 1);
    public const uint CLASSID_VIS_POINT_DEF = CLASSID_EDITOR_START + 1;
    public const uint CLASSID_PATHFIND_START_DEF = CLASSID_VIS_POINT_DEF + 1;
    public const uint CLASSID_LIGHT_DEF = CLASSID_PATHFIND_START_DEF + 1;
    public const uint CLASSID_COVERSPOT = CLASSID_LIGHT_DEF + 1;
    public const uint CLASSID_EDITOR_ONLY_OBJECTS = CLASSID_COVERSPOT + 1;
}
