namespace RenData.IDs;

public class ClassId
{
    public const int DEF_CLASSID_START = 0x00001000;
    public const int DEF_CLASSID_RANGE = 0x00001000;

    public const int CLASSID_TERRAIN = DEF_CLASSID_START + (0 * DEF_CLASSID_RANGE);
    public const int CLASSID_TILE = DEF_CLASSID_START + (1 * DEF_CLASSID_RANGE);
    public const int CLASSID_GAME_OBJECTS = DEF_CLASSID_START + (2 * DEF_CLASSID_RANGE);
    public const int CLASSID_LIGHT = DEF_CLASSID_START + (3 * DEF_CLASSID_RANGE);
    public const int CLASSID_SOUND = DEF_CLASSID_START + (4 * DEF_CLASSID_RANGE);
    public const int CLASSID_WAYPATH = DEF_CLASSID_START + (5 * DEF_CLASSID_RANGE);
    public const int CLASSID_ZONE = DEF_CLASSID_START + (6 * DEF_CLASSID_RANGE);
    public const int CLASSID_TRANSITION = DEF_CLASSID_START + (7 * DEF_CLASSID_RANGE);
    public const int CLASSID_PHYSICS = DEF_CLASSID_START + (8 * DEF_CLASSID_RANGE);
    public const int CLASSID_EDITOR_OBJECTS = DEF_CLASSID_START + (9 * DEF_CLASSID_RANGE);
    public const int CLASSID_MUNITIONS = DEF_CLASSID_START + (10 * DEF_CLASSID_RANGE);
    public const int CLASSID_DUMMY_OBJECTS = DEF_CLASSID_START + (11 * DEF_CLASSID_RANGE);
    public const int CLASSID_BUILDINGS = DEF_CLASSID_START + (12 * DEF_CLASSID_RANGE);
    public const int CLASSID_TWIDDLERS = DEF_CLASSID_START + (13 * DEF_CLASSID_RANGE);
    public const int CLASSID_GLOBAL_SETTINGS = DEF_CLASSID_START + (14 * DEF_CLASSID_RANGE);

    public const uint CLASSID_GAME_OBJECT_DEF_SOLDIER = 0x00003001;
    public const uint XXXCLASSID_GAME_OBJECT_DEF_COMMANDO = 0x00003002;
    public const uint CLASSID_GAME_OBJECT_DEF_POWERUP = 0x00003003;
    public const uint CLASSID_GAME_OBJECT_DEF_SIMPLE = 0x00003004;
    public const uint XXXCLASSID_GAME_OBJECT_DEF_SIMPLE3 = 0x00003005;
    public const uint CLASSID_GAME_OBJECT_DEF_C4 = 0x00003006;
    public const uint CLASSID_GAME_OBJECT_DEF_SAMSITE = 0x00003007;
    public const uint XXCLASSID_GAME_OBJECT_DEF_TANK = 0x00003008;
    public const uint XXCLASSID_GAME_OBJECT_DEF_TURRET = 0x00003009;
    public const uint XXCLASSID_GAME_OBJECT_DEF_BIKE = 0x0000300A;
    public const uint XXCLASSID_GAME_OBJECT_DEF_FLYING = 0x0000300B;
    public const uint XXCLASSID_GAME_OBJECT_DEF_CAR = 0x0000300C;

    public const uint CLASSID_SPAWNER_DEF = 0x0000300D;

    public const uint CLASSID_GAME_OBJECT_DEF_SCRIPT_ZONE = 0x0000300E;
    public const uint CLASSID_GAME_OBJECT_DEF_TRANSITION = 0x0000300F;

    public const uint CLASSID_GAME_OBJECT_DEF_VEHICLE = 0x00003010;
    public const uint CLASSID_GAME_OBJECT_DEF_CINEMATIC = 0x00003011;

    public const uint CLASSID_GAME_OBJECT_DEF_DAMAGE_ZONE = 0x00003012;
    public const uint CLASSID_GAME_OBJECT_DEF_SPECIAL_EFFECTS = 0x00003013;
    public const uint CLASSID_GAME_OBJECT_DEF_SAKURA_BOSS = 0x00003014;
    public const uint XXXCLASSID_GAME_OBJECT_DEF_BUILDING = 0x00003015;
    public const uint CLASSID_GAME_OBJECT_DEF_BEACON = 0x00003016;
    public const uint CLASSID_GAME_OBJECT_DEF_MENDOZA_BOSS = 0x00003017;
    public const uint CLASSID_GAME_OBJECT_DEF_RAVESHAW_BOSS = 0x00003018;

    public const uint CLASSID_DEF_WEAPON = 0x0000B001;
    public const uint CLASSID_DEF_AMMO = 0x0000B002;
    public const uint CLASSID_DEF_EXPLOSION = 0x0000B003;

    public const uint CLASSID_GAME_OBJECT_DEF_BUILDING = 0x0000D001;

    public const uint CLASSID_GAME_OBJECT_DEF_REFINERY = 0x0000D002;
    public const uint CLASSID_GAME_OBJECT_DEF_POWERPLANT = 0x0000D003;
    public const uint CLASSID_GAME_OBJECT_DEF_SOLDIER_FACTORY = 0x0000D004;
    public const uint CLASSID_GAME_OBJECT_DEF_VEHICLE_FACTORY = 0x0000D005;
    public const uint CLASSID_GAME_OBJECT_DEF_AIRSTRIP = 0x0000D006;
    public const uint CLASSID_GAME_OBJECT_DEF_WARFACTORY = 0x0000D007;
    public const uint CLASSID_GAME_OBJECT_DEF_COMCENTER = 0x0000D008;
    public const uint CLASSID_GAME_OBJECT_DEF_REPAIR_BAY = 0x0000D009;

    public const uint CLASSID_GLOBAL_SETTINGS_DEF = 0x0000F001;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_HUMAN_LOITER = 0x0000F002;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_GENERAL = 0x0000F003;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_HUD = 0x0000F004;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_EVA = 0x0000F005;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_CHAR_CLASS = 0x0000F006;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_HUMAN_ANIM_OVERRIDE = 0x0000F007;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_PURCHASE = 0x0000F008;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_TEAM_PURCHASE = 0x0000F009;
    public const uint CLASSID_GLOBAL_SETTINGS_DEF_CNCMODE = 0x0000F00A;

    public const uint CLASSID_DECOPHYSDEF = 0x00009000; // = CLASSID_PHYSICS
    public const uint CLASSID_HUMANPHYSDEF = 0x00009001;
    public const uint CLASSID_MOTORCYCLEDEF = 0x00009002;
    public const uint CLASSID_MOTORVEHICLEDEF = 0x00009003;
    public const uint CLASSID_PHYS3DEF = 0x00009004;
    public const uint CLASSID_RIGIDBODYDEF = 0x00009005;
    public const uint CLASSID_WHEELEDVEHICLEDEF = 0x00009006;
    public const uint CLASSID_STATICPHYSDEF = 0x00009007;
    public const uint CLASSID_STATICANIMPHYSDEF = 0x00009008;
    public const uint CLASSID_PROJECTILEDEF = 0x00009009;
    public const uint CLASSID_TIMEDDECOPHYSDEF = 0x0000900A;
    public const uint CLASSID_VEHICLEPHYSDEF = 0x0000900B;
    public const uint CLASSID_TRACKEDVEHICLEDEF = 0x0000900C;
    public const uint CLASSID_VTOLVEHICLEDEF = 0x0000900D;
    public const uint CLASSID_DYNAMICANIMPHYSDEF = 0x0000900E;
    public const uint CLASSID_SHAKEABLESTATICPHYSDEF = 0x0000900F;
    public const uint CLASSID_ACCESSIBLEPHYSDEF = 0x00009010;

    // External (start at CLASSID_PHYSICS + 0x80)
    public const uint CLASSID_DOORPHYSDEF = 0x00009080;
    public const uint CLASSID_ELEVATORPHYSDEF = 0x00009081;
    public const uint CLASSID_DAMAGEABLESTATICPHYSDEF = 0x00009082;
    public const uint CLASSID_BUILDINGAGGREGATEDEF = 0x00009083;

    public static uint SuperClassID_From_ClassID(uint class_id)
    {
        //
        //	Which id-range does it fall under?
        //
        var delta = class_id - DEF_CLASSID_START;
        var num_ranges = delta / DEF_CLASSID_RANGE;

        return DEF_CLASSID_START + (num_ranges * DEF_CLASSID_RANGE);
    }
}

