namespace RenData.IDs;
public enum GameObjectClassID {
    CLASSID_GAME_OBJECT_DEF_SOLDIER = ClassId.CLASSID_GAME_OBJECTS + 1,
    XXXCLASSID_GAME_OBJECT_DEF_COMMANDO,
    CLASSID_GAME_OBJECT_DEF_POWERUP,
    CLASSID_GAME_OBJECT_DEF_SIMPLE,
    XXXCLASSID_GAME_OBJECT_DEF_SIMPLE3,
    CLASSID_GAME_OBJECT_DEF_C4,
    CLASSID_GAME_OBJECT_DEF_SAMSITE,
    XXCLASSID_GAME_OBJECT_DEF_TANK,
    XXCLASSID_GAME_OBJECT_DEF_TURRET,
    XXCLASSID_GAME_OBJECT_DEF_BIKE,
    XXCLASSID_GAME_OBJECT_DEF_FLYING,
    XXCLASSID_GAME_OBJECT_DEF_CAR,

    CLASSID_SPAWNER_DEF,

    CLASSID_GAME_OBJECT_DEF_SCRIPT_ZONE,
    CLASSID_GAME_OBJECT_DEF_TRANSITION,

    CLASSID_GAME_OBJECT_DEF_VEHICLE,
    CLASSID_GAME_OBJECT_DEF_CINEMATIC,

    CLASSID_GAME_OBJECT_DEF_DAMAGE_ZONE,
    CLASSID_GAME_OBJECT_DEF_SPECIAL_EFFECTS,
    CLASSID_GAME_OBJECT_DEF_SAKURA_BOSS,
    XXXCLASSID_GAME_OBJECT_DEF_BUILDING,
    CLASSID_GAME_OBJECT_DEF_BEACON,
    CLASSID_GAME_OBJECT_DEF_MENDOZA_BOSS,
    CLASSID_GAME_OBJECT_DEF_RAVESHAW_BOSS

    // MISC DEFINITIONS
};